Models/Entrenador.cs
using System.Collections.Generic;
namespace pokemonapp.Models
{
    public class Entrenador
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Foto { get; set; }
        public Pueblo Pueblo { get; set; }

         // EF Shadow property
        public int EntrenadorId { get; set; }
        public ICollection<Pueblo> Pueblos { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace pokemonapp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Pokemon.cs
using System.Collections.Generic;

namespace pokemonapp.Models
{
    public class Pokemon
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public ICollection<Tipo> Tipos { get; set; }
    }
}

Models/PokemonContext.cs
using Microsoft.EntityFrameworkCore;

namespace pokemonapp.Models
{
    public class PokemonContext : DbContext
    {
        public DbSet<Entrenador> Entrenadores { get; set; }
        public DbSet<Pueblo> Pueblos { get; set; }
        public DbSet<Region> Regiones { get; set; }
        public DbSet<Pokemon> Pokemones { get; set; }
        public DbSet<Tipo> Tipo { get; set; }

        public PokemonContext(DbContextOptions dco) : base(dco) {

        }
    }
}

Models/Pueblo.cs
using System.Collections.Generic;

namespace pokemonapp.Models
{
    public class Pueblo
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Region Region { get; set; }

        // EF Shadow property
        public int RegionId { get; set; }
        public ICollection<Entrenador> Entrenadores { get; set; }
    }
}

Models/Region.cs
using System.Collections.Generic;

namespace pokemonapp.Models
{
    public class Region
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public ICollection<Pueblo> Pueblos { get; set; }
    }
}

Models/Tipo.cs
using System.Collections.Generic;

namespace pokemonapp.Models
{
    public class Tipo
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public ICollection<Pokemon> Pokemones { get; set; }
    }
}

Controllers/EntrenadorController.cs
namespace pokemonapp.Controllers
{
    public class EntrenadorController
    {
        
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using pokemonapp.Models;

namespace pokemonapp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UbicacionesController.cs
using Microsoft.AspNetCore.Mvc;
using pokemonapp.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace pokemonapp.Controllers
{
    public class UbicacionesController : Controller
    {
        private readonly PokemonContext _context;
        public UbicacionesController(PokemonContext context) {
            _context = context;
        }

        public IActionResult Regiones() {
            var regiones = _context.Regiones.Include(x => x.Pueblos).OrderBy(r => r.Nombre).ToList();
            return View(regiones);
        }

        public IActionResult Pueblos() {
            var pueblos = _context.Pueblos.Include(x => x.Region).OrderBy(r => r.Nombre).ToList();
            return View(pueblos);
        }

        public IActionResult NuevoPueblo() {
            ViewBag.Regiones = _context.Regiones.ToList().Select(r => new SelectListItem(r.Nombre, r.Id.ToString()));
            return View();
        }

        [HttpPost]
        public IActionResult NuevoPueblo(Pueblo r) {
            if (ModelState.IsValid) {
                _context.Add(r);
                _context.SaveChanges();
                return RedirectToAction("NuevoPuebloConfirmacion");
            }
            return View(r);
        }

        public IActionResult NuevoPuebloConfirmacion() {
            return View();
        }

        public IActionResult NuevaRegion() {
            return View();
        }

        [HttpPost]
        public IActionResult NuevaRegion(Region r) {
            if (ModelState.IsValid) {
                _context.Add(r);
                _context.SaveChanges();
                return RedirectToAction("NuevaRegionConfirmacion");
            }
            return View(r);
        }

        public IActionResult NuevaRegionConfirmacion() {
            return View();
        }

        [HttpPost]
        public IActionResult BorrarRegion(int id) {
            var region = _context.Regiones.Find(id);
            _context.Remove(region);
            _context.SaveChanges();

            return RedirectToAction("Regiones");
        }

        public IActionResult EditarRegion(int id) {
            var region = _context.Regiones.Find(id);
            return View(region);
        }

        [HttpPost]
        public IActionResult EditarRegion(Region r) {
            if (ModelState.IsValid) {
                var region = _context.Regiones.Find(r.Id);
                region.Nombre = r.Nombre;
                _context.SaveChanges();
                return RedirectToAction("EditarRegionConfirmacion");
            }
            return View(r);
        }

        public IActionResult EditarRegionConfirmacion() {
            return View();
        }
    }
}

Views/Entrenador/EditarEntrenador.cshtml
@model Entrenador


<h1>Editar región</h1>

<form action="" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" type="text" class="form-control">
        <label asp-for="Pueblo"></label>
        <input asp-for="Pueblo" type="text" class="form-control">
    </div>
    <button class="btn btn-primary">Editar</button>
</form>

Views/Entrenador/NuevoEntrenador.cshtml
@model Entrenador

<h1>Nuevo Entrenador</h1>

<form action="" method="post">
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" type="text" class="form-control">   
    </div>
    <div class="form-group">
        <label asp-for="Pueblo"></label>
        <select asp-for="EntrenadorId" asp-items="ViewBag.Regiones" type="text" class="form-control"></select>
    </div>
    <button class="btn btn-primary">Registrar</button>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - pokemonapp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">pokemonapp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ubicaciones" asp-action="NuevaRegion">Nueva Region</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ubicaciones" asp-action="NuevoPueblo">Nuevo Pueblo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - pokemonapp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Ubicaciones/EditarRegion.cshtml
@model Region

<h1>Editar región</h1>

<form action="" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" type="text" class="form-control">
    </div>
    <button class="btn btn-primary">Editar</button>
</form>

Views/Ubicaciones/EditarRegionConfirmacion.cshtml
<h1>Editar región</h1>

<p>La región fue editada con éxito</p>

Views/Ubicaciones/NuevaRegion.cshtml
@model Region

<h1>Nueva región</h1>

<form action="" method="post">
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" type="text" class="form-control">
    </div>
    <button class="btn btn-primary">Registrar</button>
</form>

Views/Ubicaciones/NuevaRegionConfirmacion.cshtml
<h1>Nueva región</h1>

<p>La región fue creada con éxito</p>

Views/Ubicaciones/NuevoPueblo.cshtml
@model Pueblo

<h1>Nuevo Pueblo</h1>

<form action="" method="post">
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Region"></label>
        <select asp-for="RegionId" asp-items="ViewBag.Regiones" type="text" class="form-control"></select>
    </div>
    <button class="btn btn-primary">Registrar</button>
</form>

Views/Ubicaciones/NuevoPuebloConfirmacion.cshtml
<h1>Nuevo Pueblo</h1>

<p>El pueblo fue creado con éxito</p>

Views/Ubicaciones/Pueblos.cshtml
@model List<Pueblo>


<h1>Lista de pueblos</h1>

<table class="table border">
    <tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>Region</th>
        <th>Operaciones</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Nombre</td>
            <td>
                @item.Region.Nombre
            </td>
            <td>
                <a href="/ubicaciones/editarregion/@item.Id" class="btn btn-secondary">Editar</a>

                <form action="/ubicaciones/borrarregion" method="post" class="d-inline-block">
                    <input type="hidden" name="id" value="@item.Id" />
                    <button class="btn btn-danger">Borrar</button>
                </form>
            </td>
        </tr>
    }
    @if (Model.Count == 0) {
        <tr>
            <td colspan="4" class="text-center">No se encontraron pueblos</td>
        </tr>
    }
</table>

<a href="/ubicaciones/nuevopueblo" class="btn btn-primary">Añadir pueblo</a>

Views/Ubicaciones/Regiones.cshtml
@model List<Region>


<h1>Lista de regiones</h1>

<table class="table border">
    <tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>Pueblos</th>
        <th>Operaciones</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Nombre</td>
            <td>
                @foreach (var pueblo in item.Pueblos)
                {
                    <span>@pueblo.Nombre</span>
                }
            </td>
            <td>
                <a href="/ubicaciones/editarregion/@item.Id" class="btn btn-secondary">Editar</a>

                <form action="/ubicaciones/borrarregion" method="post" class="d-inline-block">
                    <input type="hidden" name="id" value="@item.Id" />
                    <button class="btn btn-danger">Borrar</button>
                </form>
            </td>
        </tr>
    }
    @if (Model.Count == 0) {
        <tr>
            <td colspan="4" class="text-center">No se encontraron regiones</td>
        </tr>
    }
</table>

<a href="/ubicaciones/nuevaregion" class="btn btn-primary">Añadir región</a>